---
# Install lvm packages

- name: unwanted packages are removed
  package:
    name: "{{ lvm_packages_remove }}"
    state: absent
  become: true
  when: lvm_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ lvm_packages_repos }}"
    state: "{{ lvm_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ lvm_packages_prereq }}"
    state: "{{ lvm_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ lvm_packages_install }}"
    state: "{{ lvm_packages_state }}"
  become: true
