---
# Template configuration files for lvm

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ lvm_templates_copy }}"
  when: lvm_copy_templates
